using System;

namespace PVOutput.Net.Objects
{
    /// <summary>
    /// Describes statistics for a system.
    /// </summary>
    public interface IStatistic
    {
        /// <summary>
        /// Total energy generated by the system.
        /// </summary>
        int EnergyGenerated { get; set; }

        /// <summary>
        /// Total energy exported by the system.
        /// </summary>
        int EnergyExported { get; set; }

        /// <summary>
        /// Average energy the system generates per day.
        /// </summary>
        int AverageGeneration { get; set; }

        /// <summary>
        /// Lowest recorded generation for the system in it's lifetime.
        /// </summary>
        int MinimumGeneration { get; set; }

        /// <summary>
        /// Highest recorded generation for the system in it's lifetime.
        /// </summary>
        int MaximumGeneration { get; set; }

        /// <summary>
        /// Average efficiency the system performs at.
        /// </summary>     
        decimal AverageEfficiency { get; set; }

        /// <summary>
        /// Total number of outputs the system has recorded.
        /// </summary>
        int Outputs { get; set; }

        /// <summary>
        /// Actual minimum date the statistics are calculated over.
        /// </summary>
        DateTime ActualDateFrom { get; set; }

        /// <summary>
        /// Actual maximum date the statistics are calculated over.
        /// </summary>
        DateTime ActualDateTo { get; set; }

        /// <summary>
        /// Highest ever recorded efficiency for the system.
        /// </summary>
        decimal RecordEfficiency { get; set; }

        /// <summary>
        /// Date the <see cref="RecordEfficiency"/> was recorded at.
        /// </summary>
        DateTime RecordDate { get; set; }

        /// <summary>
        /// Total energy consumed by the system.
        /// </summary>
        int? EnergyConsumed { get; set; }

        /// <summary>
        /// Peak energy import for the system.
        /// </summary>
        int? PeakEnergyImport { get; set; }

        /// <summary>
        /// Off peak energy import for the system.
        /// </summary>
        int? OffPeakEnergyImport { get; set; }

        /// <summary>
        /// Shoulder energy import for the system.
        /// </summary>
        int? ShoulderEnergyImport { get; set; }

        /// <summary>
        /// High shoulder energy import for the system.
        /// </summary>
        int? HighShoulderEnergyImport { get; set; }

        /// <summary>
        /// Average consumption for the system.
        /// </summary>
        int? AverageConsumption { get; set; }

        /// <summary>
        /// Lowest  consumption recorded by the system.
        /// </summary>
        int? MinimumConsumption { get; set; }

        /// <summary>
        /// Highest consumption recorded by the system.
        /// </summary>
        int? MaximumConsumption { get; set; }

        /// <summary>
        /// Total credit amount for the system.
        /// </summary>
        decimal? CreditAmount { get; set; }

        /// <summary>
        /// Total debit amount for the system.
        /// </summary>
        decimal? DebitAmount { get; set; }
    }
}
