name: .NET Core

on: 
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - 'docfx/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.9.1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test

