name: .NET build

on: 
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - 'docfx/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'        
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test

